build: false
version: '0.8.0.{build}'
platform: 'x64'

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

install:
  - "%PYTHON%/Scripts/pip.exe install --requirement requirements-dev.txt"

test_script:
  - "%PYTHON%/Scripts/nose2"
