language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - 3.6
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
install:
    - pip install -r requirements-dev.txt
script:
    - nose2 --with-coverage
after_success:
    - coveralls
